services:
    web:
        build: 
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
            - ./frontend:/app/frontend
        environment:
            DJANGO_SETTINGS_MODULE: app.settings
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        depends_on:
            - db
        command: ["./wait-for-it.sh", "db:5432", "-t", "50", "--", "./django.sh"]
    db:
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_volumen:/var/lib/postgresql/data
        ports:
            - "50000:5432"
volumes:
    postgres_volumen: