services:
    web:
        build: 
            context: .
            dockerfile: backend/Dockerfile
        command: watchfiles "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
            - ./frontend:/app/frontend
        environment:
            - DJANGO_SETTINGS_MODULE=app.settings
        depends_on:
            - db
    
    db:
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_volumen:/var/lib/postgresql/data
volumes:
    postgres_volumen: